
var ortWasmThreaded = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

function e(){k.buffer!=n.buffer&&r();return n}function x(){k.buffer!=n.buffer&&r();return aa}function ba(){k.buffer!=n.buffer&&r();return ca}function z(){k.buffer!=n.buffer&&r();return da}function A(){k.buffer!=n.buffer&&r();return ea}function fa(){k.buffer!=n.buffer&&r();return ha}function B(){k.buffer!=n.buffer&&r();return ia}
var C=Object.assign({},moduleArg),ja,ka,la=new Promise((a,b)=>{ja=a;ka=b}),ma="object"==typeof window,D="function"==typeof importScripts,E="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,F=D&&"em-pthread"==self.name;if(E){const {createRequire:a}=await import("module");var require=a(import.meta.url),na=require("worker_threads");global.Worker=na.Worker;F=(D=!na.Kb)&&"em-pthread"==na.workerData}"use strict";
C.mountExternalData=(a,b)=>{a.startsWith("./")&&(a=a.substring(2));(C.cb||(C.cb=new Map)).set(a,b)};C.unmountExternalData=()=>{delete C.cb};var SharedArrayBuffer=globalThis.SharedArrayBuffer??(new WebAssembly.Memory({initial:0,maximum:0,shared:!0})).buffer.constructor;"use strict";
let pa=()=>{const a=(c,d,f)=>(...g)=>{const l=G,m=d?.();g=c(...g);const p=d?.();m!==p&&(c=p,f(m),d=f=null);return G!=l?oa():g},b=c=>async(...d)=>{try{if(C.eb)throw Error("Session already started");const f=C.eb={Bb:d[0],errors:[]},g=await c(...d);if(C.eb!==f)throw Error("Session mismatch");C.fb?.flush();const l=f.errors;if(0<l.length){let m=await Promise.all(l);m=m.filter(p=>p);if(0<m.length)throw Error(m.join("\n"));}return g}finally{C.eb=null}};C._OrtCreateSession=a(C._OrtCreateSession,()=>C._OrtCreateSession,
c=>C._OrtCreateSession=c);C._OrtRun=b(a(C._OrtRun,()=>C._OrtRun,c=>C._OrtRun=c));C._OrtRunWithBinding=b(a(C._OrtRunWithBinding,()=>C._OrtRunWithBinding,c=>C._OrtRunWithBinding=c));C._OrtBindInput=a(C._OrtBindInput,()=>C._OrtBindInput,c=>C._OrtBindInput=c);pa=void 0};
C.jsepInit=(a,b)=>{pa?.();if("webgpu"===a){[C.fb,C.qb,C.ub,C.mb,C.tb,C.Ja,C.vb,C.yb,C.rb,C.sb,C.xb]=b;const c=C.fb;C.jsepRegisterBuffer=(d,f,g,l)=>c.registerBuffer(d,f,g,l);C.jsepGetBuffer=d=>c.getBuffer(d);C.jsepCreateDownloader=(d,f,g)=>c.createDownloader(d,f,g);C.jsepOnCreateSession=d=>{c.onCreateSession(d)};C.jsepOnReleaseSession=d=>{c.onReleaseSession(d)};C.jsepOnRunStart=d=>c.onRunStart(d);C.zb=(d,f)=>{c.upload(d,f)}}else if("webnn"===a){[C.fb,C.Mb,C.wb,C.jsepEnsureTensor,C.Nb,C.jsepDownloadTensor]=
b;C.jsepReleaseTensorId=C.wb;const c=C.fb;C.jsepOnRunStart=d=>c.onRunStart(d);C.jsepRegisterMLContext=(d,f)=>{c.registerMLContext(d,f)};C.jsepOnReleaseSession=d=>{c.onReleaseSession(d)};C.jsepCreateMLTensorDownloader=(d,f)=>c.createMLTensorDownloader(d,f);C.jsepRegisterMLTensor=(d,f,g)=>c.registerMLTensor(d,f,g);C.jsepCreateMLContext=d=>c.createMLContext(d);C.Lb=(d,f,g,l,m)=>c.registerMLConstant(d,f,g,l,m,C.cb)}};var qa=Object.assign({},C),ra="./this.program",sa=(a,b)=>{throw b;},H="",ta,ua,va;
if(E){var fs=require("fs"),wa=require("path");H=require("url").fileURLToPath(new URL("./",import.meta.url));ta=(a,b)=>{a=xa(a)?new URL(a):wa.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};va=a=>{a=ta(a,!0);a.buffer||(a=new Uint8Array(a));return a};ua=(a,b,c,d=!0)=>{a=xa(a)?new URL(a):wa.normalize(a);fs.readFile(a,d?void 0:"utf8",(f,g)=>{f?c(f):b(d?g.buffer:g)})};!C.thisProgram&&1<process.argv.length&&(ra=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);sa=(a,b)=>{process.exitCode=
a;throw b;}}else if(ma||D)D?H=self.location.href:"undefined"!=typeof document&&document.currentScript&&(H=document.currentScript.src),_scriptName&&(H=_scriptName),H.startsWith("blob:")?H="":H=H.substr(0,H.replace(/[?#].*/,"").lastIndexOf("/")+1),E||(ta=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},D&&(va=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ua=(a,b,c)=>{var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)});E&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var ya=console.log.bind(console),za=console.error.bind(console);E&&(ya=(...a)=>fs.writeSync(1,a.join(" ")+"\n"),za=(...a)=>fs.writeSync(2,a.join(" ")+"\n"));var Aa=ya,I=za;Object.assign(C,qa);qa=null;
if(F){var Ba;if(E){var Ca=na.parentPort;Ca.on("message",b=>onmessage({data:b}));Object.assign(globalThis,{self:global,importScripts:()=>{},postMessage:b=>Ca.postMessage(b),performance:global.performance||{now:Date.now}})}var Da=!1;I=function(...b){b=b.join(" ");E?fs.writeSync(2,b+"\n"):console.error(b)};self.alert=function(...b){postMessage({lb:"alert",text:b.join(" "),Ob:J()})};C.instantiateWasm=(b,c)=>new Promise(d=>{Ba=f=>{f=new WebAssembly.Instance(f,Ea());c(f);d()}});self.onunhandledrejection=
b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.cmd;if("load"===d){let f=[];self.onmessage=g=>f.push(g);self.startWorker=()=>{postMessage({cmd:"loaded"});for(let g of f)a(g);self.onmessage=a};for(const g of c.handlers)if(!C[g]||C[g].proxy)C[g]=(...l)=>{postMessage({lb:"callHandler",Jb:g,args:l})},"print"==g&&(Aa=C[g]),"printErr"==g&&(I=C[g]);k=c.wasmMemory;r();Ba(c.wasmModule)}else if("run"===d){Fa(c.pthread_ptr,0,0,1,0,0);Ga(c.pthread_ptr);Ha();Ia();Da||=!0;try{Ja(c.start_routine,c.arg)}catch(f){if("unwind"!=
f)throw f;}}else"cancel"===d?J()&&Ka(-1):"setimmediate"!==c.target&&("checkMailbox"===d?Da&&La():d&&(I(`worker: received unknown command ${d}`),I(c)))}catch(f){throw Ma(),f;}}self.onmessage=a}var Na;C.wasmBinary&&(Na=C.wasmBinary);var k,Oa,K=!1,L,n,aa,ca,da,ea,ha,M,ia;
function r(){var a=k.buffer;C.HEAP8=n=new Int8Array(a);C.HEAP16=ca=new Int16Array(a);C.HEAPU8=aa=new Uint8Array(a);C.HEAPU16=new Uint16Array(a);C.HEAP32=da=new Int32Array(a);C.HEAPU32=ea=new Uint32Array(a);C.HEAPF32=ha=new Float32Array(a);C.HEAPF64=ia=new Float64Array(a);C.HEAP64=M=new BigInt64Array(a);C.HEAPU64=new BigUint64Array(a)}
if(!F){k=new WebAssembly.Memory({initial:256,maximum:65536,shared:!0});if(!(k.buffer instanceof SharedArrayBuffer))throw I("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),E&&I("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),Error("bad memory");r()}
var Pa=[],Qa=[],Ra=[],N=0,Sa=null,Ta=null;function Ua(){N--;if(0==N&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}function O(a){a="Aborted("+a+")";I(a);K=!0;L=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ka(a);throw a;}var Va=a=>a.startsWith("data:application/octet-stream;base64,"),xa=a=>a.startsWith("file://"),Wa;
function Xa(a){if(a==Wa&&Na)return new Uint8Array(Na);if(va)return va(a);throw"both async and sync fetching of the wasm failed";}function Ya(a){if(!Na&&(ma||D)){if("function"==typeof fetch&&!xa(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Xa(a));if(ua)return new Promise((b,c)=>{ua(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Xa(a))}
function Za(a,b,c){return Ya(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{I(`failed to asynchronously prepare wasm: ${d}`);O(d)})}function $a(a,b){var c=Wa;return Na||"function"!=typeof WebAssembly.instantiateStreaming||Va(c)||xa(c)||E||"function"!=typeof fetch?Za(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){I(`wasm streaming compile failed: ${f}`);I("falling back to ArrayBuffer instantiation");return Za(c,a,b)}))}
function Ea(){ab={k:bb,w:cb,b:db,E:eb,h:fb,V:gb,A:hb,C:ib,W:jb,T:kb,L:lb,S:mb,q:nb,B:ob,y:pb,U:qb,z:rb,_:sb,Z:tb,O:ub,v:vb,F:wb,l:xb,N:Ga,Y:yb,I:zb,J:Ab,K:Bb,G:Cb,H:Db,u:Eb,c:Fb,n:Gb,m:Hb,r:Ib,f:Jb,X:Kb,x:Lb,e:Mb,g:Nb,j:Ob,t:Pb,s:Qb,aa:Rb,Q:Sb,R:Tb,D:Ub,i:Vb,p:Wb,M:Xb,o:Yb,a:k,$:Zb,P:$b,d:ac};return{a:ab}}
var bc={801276:(a,b,c,d,f)=>{if("undefined"==typeof C||!C.cb)return 1;a=P(Number(a>>>0));a.startsWith("./")&&(a=a.substring(2));a=C.cb.get(a);if(!a)return 2;b=Number(b>>>0);c=Number(c>>>0);d=Number(d>>>0);if(b+c>a.byteLength)return 3;try{const g=a.subarray(b,b+c);switch(f){case 0:x().set(g,d>>>0);break;case 1:C.zb(d,g);break;default:return 4}return 0}catch{return 4}},801991:()=>{C.rb()},802022:()=>{C.sb()},802051:()=>{C.xb()},802076:a=>C.qb(a),802109:a=>C.ub(a),802141:(a,b,c)=>{C.mb(Number(a),Number(b),
Number(c),!0)},802204:(a,b,c)=>{C.mb(Number(a),Number(b),Number(c))},802261:()=>"undefined"!==typeof wasmOffsetConverter,802318:a=>{C.Ja("Abs",a,void 0)},802369:a=>{C.Ja("Neg",a,void 0)},802420:a=>{C.Ja("Floor",a,void 0)},802473:a=>{C.Ja("Ceil",a,void 0)},802525:a=>{C.Ja("Reciprocal",a,void 0)},802583:a=>{C.Ja("Sqrt",a,void 0)},802635:a=>{C.Ja("Exp",a,void 0)},802686:a=>{C.Ja("Erf",a,void 0)},802737:a=>{C.Ja("Sigmoid",a,void 0)},802792:(a,b,c)=>{C.Ja("HardSigmoid",a,{alpha:b,beta:c})},802871:a=>{C.Ja("Log",
a,void 0)},802922:a=>{C.Ja("Sin",a,void 0)},802973:a=>{C.Ja("Cos",a,void 0)},803024:a=>{C.Ja("Tan",a,void 0)},803075:a=>{C.Ja("Asin",a,void 0)},803127:a=>{C.Ja("Acos",a,void 0)},803179:a=>{C.Ja("Atan",a,void 0)},803231:a=>{C.Ja("Sinh",a,void 0)},803283:a=>{C.Ja("Cosh",a,void 0)},803335:a=>{C.Ja("Asinh",a,void 0)},803388:a=>{C.Ja("Acosh",a,void 0)},803441:a=>{C.Ja("Atanh",a,void 0)},803494:a=>{C.Ja("Tanh",a,void 0)},803546:a=>{C.Ja("Not",a,void 0)},803597:(a,b,c)=>{C.Ja("Clip",a,{min:b,max:c})},803666:a=>
{C.Ja("Clip",a,void 0)},803718:(a,b)=>{C.Ja("Elu",a,{alpha:b})},803776:a=>{C.Ja("Gelu",a,void 0)},803828:a=>{C.Ja("Relu",a,void 0)},803880:(a,b)=>{C.Ja("LeakyRelu",a,{alpha:b})},803944:(a,b)=>{C.Ja("ThresholdedRelu",a,{alpha:b})},804014:(a,b)=>{C.Ja("Cast",a,{to:b})},804072:a=>{C.Ja("Add",a,void 0)},804123:a=>{C.Ja("Sub",a,void 0)},804174:a=>{C.Ja("Mul",a,void 0)},804225:a=>{C.Ja("Div",a,void 0)},804276:a=>{C.Ja("Pow",a,void 0)},804327:a=>{C.Ja("Equal",a,void 0)},804380:a=>{C.Ja("Greater",a,void 0)},
804435:a=>{C.Ja("GreaterOrEqual",a,void 0)},804497:a=>{C.Ja("Less",a,void 0)},804549:a=>{C.Ja("LessOrEqual",a,void 0)},804608:(a,b,c,d,f)=>{C.Ja("ReduceMean",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},804783:(a,b,c,d,f)=>{C.Ja("ReduceMax",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},804957:(a,b,c,d,f)=>{C.Ja("ReduceMin",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>
0,Number(f)>>>0)):[]})},805131:(a,b,c,d,f)=>{C.Ja("ReduceProd",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},805306:(a,b,c,d,f)=>{C.Ja("ReduceSum",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},805480:(a,b,c,d,f)=>{C.Ja("ReduceL1",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},805653:(a,b,c,d,f)=>{C.Ja("ReduceL2",a,{keepDims:!!b,
noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},805826:(a,b,c,d,f)=>{C.Ja("ReduceLogSum",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},806003:(a,b,c,d,f)=>{C.Ja("ReduceSumSquare",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},806183:(a,b,c,d,f)=>{C.Ja("ReduceLogSumExp",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>
0,Number(f)>>>0)):[]})},806363:a=>{C.Ja("Where",a,void 0)},806416:(a,b,c)=>{C.Ja("Transpose",a,{perm:b?Array.from(z().subarray(Number(b)>>>0,Number(c)>>>0)):[]})},806540:(a,b,c,d)=>{C.Ja("DepthToSpace",a,{blocksize:b,mode:P(c),format:d?"NHWC":"NCHW"})},806673:(a,b,c,d)=>{C.Ja("DepthToSpace",a,{blocksize:b,mode:P(c),format:d?"NHWC":"NCHW"})},806806:(a,b,c,d,f,g,l,m,p,q,t,v,y,h,u)=>{C.Ja("ConvTranspose",a,{format:p?"NHWC":"NCHW",autoPad:b,dilations:[c],group:d,kernelShape:[f],pads:[g,l],strides:[m],
wIsConst:()=>!!e()[q>>>0],outputPadding:t?Array.from(z().subarray(Number(t)>>>0,Number(v)>>>0)):[],outputShape:y?Array.from(z().subarray(Number(y)>>>0,Number(h)>>>0)):[],activation:P(u)})},807239:(a,b,c,d,f,g,l,m,p,q,t,v,y,h)=>{C.Ja("ConvTranspose",a,{format:m?"NHWC":"NCHW",autoPad:b,dilations:Array.from(z().subarray(Number(c)>>>0,(Number(c)>>>0)+2>>>0)),group:d,kernelShape:Array.from(z().subarray(Number(f)>>>0,(Number(f)>>>0)+2>>>0)),pads:Array.from(z().subarray(Number(g)>>>0,(Number(g)>>>0)+4>>>
0)),strides:Array.from(z().subarray(Number(l)>>>0,(Number(l)>>>0)+2>>>0)),wIsConst:()=>!!e()[p>>>0],outputPadding:q?Array.from(z().subarray(Number(q)>>>0,Number(t)>>>0)):[],outputShape:v?Array.from(z().subarray(Number(v)>>>0,Number(y)>>>0)):[],activation:P(h)})},807900:(a,b,c,d,f,g,l,m,p,q,t,v,y,h,u)=>{C.Ja("ConvTranspose",a,{format:p?"NHWC":"NCHW",autoPad:b,dilations:[c],group:d,kernelShape:[f],pads:[g,l],strides:[m],wIsConst:()=>!!e()[q>>>0],outputPadding:t?Array.from(z().subarray(Number(t)>>>0,
Number(v)>>>0)):[],outputShape:y?Array.from(z().subarray(Number(y)>>>0,Number(h)>>>0)):[],activation:P(u)})},808333:(a,b,c,d,f,g,l,m,p,q,t,v,y,h)=>{C.Ja("ConvTranspose",a,{format:m?"NHWC":"NCHW",autoPad:b,dilations:Array.from(z().subarray(Number(c)>>>0,(Number(c)>>>0)+2>>>0)),group:d,kernelShape:Array.from(z().subarray(Number(f)>>>0,(Number(f)>>>0)+2>>>0)),pads:Array.from(z().subarray(Number(g)>>>0,(Number(g)>>>0)+4>>>0)),strides:Array.from(z().subarray(Number(l)>>>0,(Number(l)>>>0)+2>>>0)),wIsConst:()=>
!!e()[p>>>0],outputPadding:q?Array.from(z().subarray(Number(q)>>>0,Number(t)>>>0)):[],outputShape:v?Array.from(z().subarray(Number(v)>>>0,Number(y)>>>0)):[],activation:P(h)})},808994:(a,b)=>{C.Ja("GlobalAveragePool",a,{format:b?"NHWC":"NCHW"})},809085:(a,b,c,d,f,g,l,m,p,q,t,v,y,h)=>{C.Ja("AveragePool",a,{format:h?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:d,storage_order:f,dilations:g?Array.from(z().subarray(Number(g)>>>0,Number(l)>>>0)):[],kernel_shape:m?Array.from(z().subarray(Number(m)>>>
0,Number(p)>>>0)):[],pads:q?Array.from(z().subarray(Number(q)>>>0,Number(t)>>>0)):[],strides:v?Array.from(z().subarray(Number(v)>>>0,Number(y)>>>0)):[]})},809564:(a,b)=>{C.Ja("GlobalAveragePool",a,{format:b?"NHWC":"NCHW"})},809655:(a,b,c,d,f,g,l,m,p,q,t,v,y,h)=>{C.Ja("AveragePool",a,{format:h?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:d,storage_order:f,dilations:g?Array.from(z().subarray(Number(g)>>>0,Number(l)>>>0)):[],kernel_shape:m?Array.from(z().subarray(Number(m)>>>0,Number(p)>>>
0)):[],pads:q?Array.from(z().subarray(Number(q)>>>0,Number(t)>>>0)):[],strides:v?Array.from(z().subarray(Number(v)>>>0,Number(y)>>>0)):[]})},810134:(a,b)=>{C.Ja("GlobalMaxPool",a,{format:b?"NHWC":"NCHW"})},810221:(a,b,c,d,f,g,l,m,p,q,t,v,y,h)=>{C.Ja("MaxPool",a,{format:h?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:d,storage_order:f,dilations:g?Array.from(z().subarray(Number(g)>>>0,Number(l)>>>0)):[],kernel_shape:m?Array.from(z().subarray(Number(m)>>>0,Number(p)>>>0)):[],pads:q?Array.from(z().subarray(Number(q)>>>
0,Number(t)>>>0)):[],strides:v?Array.from(z().subarray(Number(v)>>>0,Number(y)>>>0)):[]})},810696:(a,b)=>{C.Ja("GlobalMaxPool",a,{format:b?"NHWC":"NCHW"})},810783:(a,b,c,d,f,g,l,m,p,q,t,v,y,h)=>{C.Ja("MaxPool",a,{format:h?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:d,storage_order:f,dilations:g?Array.from(z().subarray(Number(g)>>>0,Number(l)>>>0)):[],kernel_shape:m?Array.from(z().subarray(Number(m)>>>0,Number(p)>>>0)):[],pads:q?Array.from(z().subarray(Number(q)>>>0,Number(t)>>>0)):[],strides:v?
Array.from(z().subarray(Number(v)>>>0,Number(y)>>>0)):[]})},811258:(a,b,c,d,f)=>{C.Ja("Gemm",a,{alpha:b,beta:c,transA:d,transB:f})},811362:a=>{C.Ja("MatMul",a,void 0)},811416:(a,b,c,d)=>{C.Ja("ArgMax",a,{keepDims:!!b,selectLastIndex:!!c,axis:d})},811524:(a,b,c,d)=>{C.Ja("ArgMin",a,{keepDims:!!b,selectLastIndex:!!c,axis:d})},811632:(a,b)=>{C.Ja("Softmax",a,{axis:b})},811695:(a,b)=>{C.Ja("Concat",a,{axis:b})},811755:(a,b,c,d,f)=>{C.Ja("Split",a,{axis:b,numOutputs:c,splitSizes:d?Array.from(z().subarray(Number(d)>>>
0,Number(f)>>>0)):[]})},811911:a=>{C.Ja("Expand",a,void 0)},811965:(a,b)=>{C.Ja("Gather",a,{axis:Number(b)})},812036:(a,b)=>{C.Ja("GatherElements",a,{axis:Number(b)})},812115:(a,b,c,d,f,g,l,m,p,q,t)=>{C.Ja("Resize",a,{antialias:b,axes:c?Array.from(z().subarray(Number(c)>>>0,Number(d)>>>0)):[],coordinateTransformMode:P(f),cubicCoeffA:g,excludeOutside:l,extrapolationValue:m,keepAspectRatioPolicy:P(p),mode:P(q),nearestMode:P(t)})},812477:(a,b,c,d,f,g,l)=>{C.Ja("Slice",a,{starts:b?Array.from(z().subarray(Number(b)>>>
0,Number(c)>>>0)):[],ends:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[],axes:g?Array.from(z().subarray(Number(g)>>>0,Number(l)>>>0)):[]})},812741:a=>{C.Ja("Tile",a,void 0)},812793:(a,b,c)=>{C.Ja("InstanceNormalization",a,{epsilon:b,format:c?"NHWC":"NCHW"})},812907:(a,b,c)=>{C.Ja("InstanceNormalization",a,{epsilon:b,format:c?"NHWC":"NCHW"})},813021:a=>{C.Ja("Range",a,void 0)},813074:(a,b)=>{C.Ja("Einsum",a,{equation:P(b)})},813155:(a,b,c,d,f)=>{C.Ja("Pad",a,{mode:b,value:c,pads:d?Array.from(z().subarray(Number(d)>>>
0,Number(f)>>>0)):[]})},813298:(a,b,c,d,f,g)=>{C.Ja("BatchNormalization",a,{epsilon:b,momentum:c,spatial:!!f,trainingMode:!!d,format:g?"NHWC":"NCHW"})},813467:(a,b,c,d,f,g)=>{C.Ja("BatchNormalization",a,{epsilon:b,momentum:c,spatial:!!f,trainingMode:!!d,format:g?"NHWC":"NCHW"})},813636:(a,b,c)=>{C.Ja("CumSum",a,{exclusive:Number(b),reverse:Number(c)})},813733:(a,b,c)=>{C.Ja("DequantizeLinear",a,{axis:b,blockSize:c})},813823:(a,b,c,d,f)=>{C.Ja("GridSample",a,{align_corners:b,mode:P(c),padding_mode:P(d),
format:f?"NHWC":"NCHW"})},813993:(a,b,c,d,f)=>{C.Ja("GridSample",a,{align_corners:b,mode:P(c),padding_mode:P(d),format:f?"NHWC":"NCHW"})},814163:(a,b,c,d,f,g,l,m,p)=>{C.Ja("Attention",a,{numHeads:b,isUnidirectional:c,maskFilterValue:d,scale:f,doRotary:g,qkvHiddenSizes:l?Array.from(z().subarray(Number(m)>>>0,Number(m)+l>>>0)):[],pastPresentShareBuffer:!!p})},814435:a=>{C.Ja("BiasAdd",a,void 0)},814490:a=>{C.Ja("BiasSplitGelu",a,void 0)},814551:a=>{C.Ja("FastGelu",a,void 0)},814607:(a,b,c,d,f,g,l,m,
p,q,t,v,y,h,u,w)=>{C.Ja("Conv",a,{format:v?"NHWC":"NCHW",auto_pad:b,dilations:c?Array.from(z().subarray(Number(c)>>>0,Number(d)>>>0)):[],group:f,kernel_shape:g?Array.from(z().subarray(Number(g)>>>0,Number(l)>>>0)):[],pads:m?Array.from(z().subarray(Number(m)>>>0,Number(p)>>>0)):[],strides:q?Array.from(z().subarray(Number(q)>>>0,Number(t)>>>0)):[],w_is_const:()=>!!e()[Number(y)>>>0],activation:P(h),activation_params:u?Array.from(fa().subarray(Number(u)>>>0,Number(w)>>>0)):[]})},815191:a=>{C.Ja("Gelu",
a,void 0)},815243:(a,b,c,d,f,g,l,m,p)=>{C.Ja("GroupQueryAttention",a,{numHeads:b,kvNumHeads:c,scale:d,softcap:f,doRotary:g,rotaryInterleaved:l,smoothSoftmax:m,localWindowSize:p})},815460:(a,b,c,d)=>{C.Ja("LayerNormalization",a,{axis:b,epsilon:c,simplified:!!d})},815571:(a,b,c,d)=>{C.Ja("LayerNormalization",a,{axis:b,epsilon:c,simplified:!!d})},815682:(a,b,c,d,f,g)=>{C.Ja("MatMulNBits",a,{k:b,n:c,accuracyLevel:d,bits:f,blockSize:g})},815809:(a,b,c,d,f,g)=>{C.Ja("MultiHeadAttention",a,{numHeads:b,isUnidirectional:c,
maskFilterValue:d,scale:f,doRotary:g})},815968:(a,b)=>{C.Ja("QuickGelu",a,{alpha:b})},816032:(a,b,c,d,f)=>{C.Ja("RotaryEmbedding",a,{interleaved:!!b,numHeads:c,rotaryEmbeddingDim:d,scale:f})},816171:(a,b,c)=>{C.Ja("SkipLayerNormalization",a,{epsilon:b,simplified:!!c})},816273:(a,b,c)=>{C.Ja("SkipLayerNormalization",a,{epsilon:b,simplified:!!c})},816375:(a,b,c,d)=>{C.Ja("GatherBlockQuantized",a,{gatherAxis:b,quantizeAxis:c,blockSize:d})},816496:a=>{C.vb(a)},816530:(a,b)=>C.yb(Number(a),Number(b),C.eb.Bb,
C.eb.errors)};function cb(a,b,c){return cc(async()=>{await C.tb(Number(a),Number(b),Number(c))})}function bb(){return"undefined"!==typeof wasmOffsetConverter}function dc(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var ec=a=>{a.terminate();a.onmessage=()=>{}},hc=a=>{0==Q.length&&(fc(),gc(Q[0]));var b=Q.pop();if(!b)return 6;R.push(b);T[a.$a]=b;b.$a=a.$a;var c={cmd:"run",start_routine:a.Cb,arg:a.ob,pthread_ptr:a.$a};E&&b.unref();b.postMessage(c,a.Hb);return 0},U=0,V=(a,b,...c)=>{for(var d=2*c.length,f=ic(),g=kc(8*d),l=g>>>3,m=0;m<c.length;m++){var p=c[m];"bigint"==typeof p?(M[l+2*m]=1n,M[l+2*m+1]=p):(M[l+2*m]=0n,B()[l+2*m+1>>>0]=p)}a=lc(a,0,d,g,b);mc(f);return a};
function Zb(a){if(F)return V(0,1,a);L=a;if(!(0<U)){for(var b of R)ec(b);for(b of Q)ec(b);Q=[];R=[];T=[];K=!0}sa(a,new dc(a))}function nc(a){if(F)return V(1,0,a);Ub(a)}var Ub=a=>{L=a;if(F)throw nc(a),"unwind";Zb(a)},Q=[],R=[],oc=[],T={};function pc(){for(var a=C.numThreads-1;a--;)fc();Pa.unshift(()=>{N++;qc(()=>Ua())})}var sc=a=>{var b=a.$a;delete T[b];Q.push(a);R.splice(R.indexOf(a),1);a.$a=0;rc(b)};function Ia(){oc.forEach(a=>a())}
var gc=a=>new Promise(b=>{a.onmessage=g=>{g=g.data;var l=g.cmd;if(g.targetThread&&g.targetThread!=J()){var m=T[g.targetThread];m?m.postMessage(g,g.transferList):I(`Internal error! Worker sent a message "${l}" to target pthread ${g.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===l)La();else if("spawnThread"===l)hc(g);else if("cleanupThread"===l)sc(T[g.thread]);else if("killThread"===l)g=g.thread,l=T[g],delete T[g],ec(l),rc(g),R.splice(R.indexOf(l),1),l.$a=0;else if("cancelThread"===
l)T[g.thread].postMessage({cmd:"cancel"});else if("loaded"===l)a.loaded=!0,E&&!a.$a&&a.unref(),b(a);else if("alert"===l)alert(`Thread ${g.threadId}: ${g.text}`);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===l)C[g.handler](...g.args);else l&&I(`worker sent an unknown command ${l}`)};a.onerror=g=>{I(`${"worker sent an error!"} ${g.filename}:${g.lineno}: ${g.message}`);throw g;};E&&(a.on("message",g=>a.onmessage({data:g})),a.on("error",g=>a.onerror(g)));var c=[],d=[],f;for(f of d)C.hasOwnProperty(f)&&
c.push(f);a.postMessage({cmd:"load",handlers:c,wasmMemory:k,wasmModule:Oa})});function qc(a){F?a():Promise.all(Q.map(gc)).then(a)}function fc(){var a=new Worker(new URL(import.meta.url),{type:"module",workerData:"em-pthread",name:"em-pthread"});Q.push(a)}var tc=a=>{for(;0<a.length;)a.shift()(C)},Ha=()=>{var a=J(),b=A()[a+52>>>2>>>0];a=A()[a+56>>>2>>>0];uc(b,b-a);mc(b)},Ja=(a,b)=>{U=0;a=vc(a,b);0<U?L=a:Ka(a)};class wc{constructor(a){this.ib=a-24}}var xc=0,yc=0;
function db(a,b,c){a>>>=0;var d=new wc(a);b>>>=0;c>>>=0;A()[d.ib+16>>>2>>>0]=0;A()[d.ib+4>>>2>>>0]=b;A()[d.ib+8>>>2>>>0]=c;xc=a;yc++;throw xc;}function zc(a,b,c,d){return F?V(2,1,a,b,c,d):eb(a,b,c,d)}
function eb(a,b,c,d){a>>>=0;b>>>=0;c>>>=0;d>>>=0;if("undefined"==typeof SharedArrayBuffer)return I("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[];if(F&&0===f.length)return zc(a,b,c,d);a={Cb:c,$a:a,ob:d,Hb:f};return F?(a.lb="spawnThread",postMessage(a,f),0):hc(a)}
var Ac="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,Bc=(a,b,c)=>{b>>>=0;var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ac)return Ac.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>
10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},P=(a,b)=>(a>>>=0)?Bc(x(),a,b):"";function fb(a,b,c){return F?V(3,1,a,b,c):0}function gb(a,b){if(F)return V(4,1,a,b)}
var Cc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Dc=(a,b,c,d)=>{c>>>=0;if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var m=a.charCodeAt(++g);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=d)break;b[c++>>>0]=l}else{if(2047>=l){if(c+1>=d)break;b[c++>>>0]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++>>>0]=224|l>>12}else{if(c+3>=d)break;b[c++>>>0]=240|l>>
18;b[c++>>>0]=128|l>>12&63}b[c++>>>0]=128|l>>6&63}b[c++>>>0]=128|l&63}}b[c>>>0]=0;return c-f},Ec=(a,b,c)=>Dc(a,x(),b,c);function hb(a,b){if(F)return V(5,1,a,b)}function ib(a,b,c){if(F)return V(6,1,a,b,c)}function jb(a,b,c){return F?V(7,1,a,b,c):0}function kb(a,b){if(F)return V(8,1,a,b)}function lb(a,b,c){if(F)return V(9,1,a,b,c)}function mb(a,b,c,d){if(F)return V(10,1,a,b,c,d)}function nb(a,b,c,d){if(F)return V(11,1,a,b,c,d)}function ob(a,b,c,d){if(F)return V(12,1,a,b,c,d)}
function pb(a){if(F)return V(13,1,a)}function qb(a,b){if(F)return V(14,1,a,b)}function rb(a,b,c){if(F)return V(15,1,a,b,c)}var sb=()=>{O("")},tb=()=>1;function ub(a){Fa(a>>>0,!D,1,!ma,131072,!1);Ia()}var Fc=a=>{if(!K)try{if(a(),!(0<U))try{F?Ka(L):Ub(L)}catch(b){b instanceof dc||"unwind"==b||sa(1,b)}}catch(b){b instanceof dc||"unwind"==b||sa(1,b)}};function Ga(a){a>>>=0;"function"===typeof Atomics.Ib&&(Atomics.Ib(z(),a>>>2,a).value.then(La),a+=128,Atomics.store(z(),a>>>2,1))}
var La=()=>{var a=J();a&&(Ga(a),Fc(Gc))};function vb(a,b){a>>>=0;a==b>>>0?setTimeout(La):F?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=T[a])&&a.postMessage({cmd:"checkMailbox"})}var Hc=[];function wb(a,b,c,d,f){b>>>=0;d/=2;Hc.length=d;c=f>>>0>>>3;for(f=0;f<d;f++)Hc[f]=M[c+2*f]?M[c+2*f+1]:B()[c+2*f+1>>>0];return(b?bc[b]:Ic[a])(...Hc)}function xb(a){a>>>=0;F?postMessage({cmd:"cleanupThread",thread:a}):sc(T[a])}function yb(a){E&&T[a>>>0].ref()}
function zb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);z()[b>>>2>>>0]=a.getUTCSeconds();z()[b+4>>>2>>>0]=a.getUTCMinutes();z()[b+8>>>2>>>0]=a.getUTCHours();z()[b+12>>>2>>>0]=a.getUTCDate();z()[b+16>>>2>>>0]=a.getUTCMonth();z()[b+20>>>2>>>0]=a.getUTCFullYear()-1900;z()[b+24>>>2>>>0]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;z()[b+28>>>2>>>0]=a}
var W=a=>0===a%4&&(0!==a%100||0===a%400),Jc=[0,31,60,91,121,152,182,213,244,274,305,335],Kc=[0,31,59,90,120,151,181,212,243,273,304,334];
function Ab(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);z()[b>>>2>>>0]=a.getSeconds();z()[b+4>>>2>>>0]=a.getMinutes();z()[b+8>>>2>>>0]=a.getHours();z()[b+12>>>2>>>0]=a.getDate();z()[b+16>>>2>>>0]=a.getMonth();z()[b+20>>>2>>>0]=a.getFullYear()-1900;z()[b+24>>>2>>>0]=a.getDay();var c=(W(a.getFullYear())?Jc:Kc)[a.getMonth()]+a.getDate()-1|0;z()[b+28>>>2>>>0]=c;z()[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();
var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;z()[b+32>>>2>>>0]=a}
function Bb(a){a>>>=0;var b=new Date(z()[a+20>>>2>>>0]+1900,z()[a+16>>>2>>>0],z()[a+12>>>2>>>0],z()[a+8>>>2>>>0],z()[a+4>>>2>>>0],z()[a>>>2>>>0],0),c=z()[a+32>>>2>>>0],d=b.getTimezoneOffset(),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),l=Math.min(g,f);0>c?z()[a+32>>>2>>>0]=Number(f!=g&&l==d):0<c!=(l==d)&&(f=Math.max(g,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));z()[a+24>>>2>>>0]=b.getDay();c=(W(b.getFullYear())?Jc:Kc)[b.getMonth()]+
b.getDate()-1|0;z()[a+28>>>2>>>0]=c;z()[a>>>2>>>0]=b.getSeconds();z()[a+4>>>2>>>0]=b.getMinutes();z()[a+8>>>2>>>0]=b.getHours();z()[a+12>>>2>>>0]=b.getDate();z()[a+16>>>2>>>0]=b.getMonth();z()[a+20>>>2>>>0]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)}function Cb(a,b,c,d,f,g,l){return F?V(16,1,a,b,c,d,f,g,l):-52}function Db(a,b,c,d,f,g){if(F)return V(17,1,a,b,c,d,f,g)}
function Eb(a,b,c,d){a>>>=0;b>>>=0;c>>>=0;d>>>=0;var f=(new Date).getFullYear(),g=new Date(f,0,1),l=new Date(f,6,1);f=g.getTimezoneOffset();var m=l.getTimezoneOffset(),p=Math.max(f,m);A()[a>>>2>>>0]=60*p;z()[b>>>2>>>0]=Number(f!=m);a=q=>q.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];g=a(g);l=a(l);m<f?(Ec(g,c,17),Ec(l,d,17)):(Ec(g,d,17),Ec(l,c,17))}
var Lc=[],Mc=(a,b)=>{Lc.length=0;for(var c;c=x()[a++>>>0];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Lc.push(112==c?A()[b>>>2>>>0]:106==c?M[b>>>3]:105==c?z()[b>>>2>>>0]:B()[b>>>3>>>0]);b+=d?8:4}return Lc};function Fb(a,b,c){a>>>=0;b=Mc(b>>>0,c>>>0);return bc[a](...b)}function Gb(a,b,c){a>>>=0;b=Mc(b>>>0,c>>>0);return bc[a](...b)}var Hb=()=>{},Ib=()=>Date.now();function Jb(a,b){return I(P(a>>>0,b>>>0))}var Kb=()=>{U+=1;throw"unwind";};function Lb(){return 4294901760}var Mb;
Mb=()=>performance.timeOrigin+performance.now();var Nb=()=>E?require("os").cpus().length:navigator.hardwareConcurrency;function Ob(){O("Cannot use emscripten_pc_get_function without -sUSE_OFFSET_CONVERTER");return 0}
function Pb(a){a>>>=0;var b=x().length;if(a<=b||4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var f=Math;d=Math.max(a,d);a:{f=(f.min.call(f,4294901760,d+(65536-d%65536)%65536)-k.buffer.byteLength+65535)/65536;try{k.grow(f);r();var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1}var Nc=()=>{O("Cannot use convertFrameToPC (needed by __builtin_return_address) without -sUSE_OFFSET_CONVERTER");return 0},X={},Oc=a=>{a.forEach(b=>{var c=Nc();c&&(X[c]=b)})};
function Qb(){var a=Error().stack.toString().split("\n");"Error"==a[0]&&a.shift();Oc(a);X.nb=Nc();X.Ab=a;return X.nb}function Rb(a,b,c){a>>>=0;b>>>=0;if(X.nb==a)var d=X.Ab;else d=Error().stack.toString().split("\n"),"Error"==d[0]&&d.shift(),Oc(d);for(var f=3;d[f]&&Nc()!=a;)++f;for(a=0;a<c&&d[a+f];++a)z()[b+4*a>>>2>>>0]=Nc();return a}
var Pc={},Rc=()=>{if(!Qc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ra||"./this.program"},b;for(b in Pc)void 0===Pc[b]?delete a[b]:a[b]=Pc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Qc=c}return Qc},Qc;
function Sb(a,b){if(F)return V(18,1,a,b);a>>>=0;b>>>=0;var c=0;Rc().forEach((d,f)=>{var g=b+c;f=A()[a+4*f>>>2>>>0]=g;for(g=0;g<d.length;++g)e()[f++>>>0]=d.charCodeAt(g);e()[f>>>0]=0;c+=d.length+1});return 0}function Tb(a,b){if(F)return V(19,1,a,b);a>>>=0;b>>>=0;var c=Rc();A()[a>>>2>>>0]=c.length;var d=0;c.forEach(f=>d+=f.length+1);A()[b>>>2>>>0]=d;return 0}function Vb(a){return F?V(20,1,a):52}function Wb(a,b,c,d){return F?V(21,1,a,b,c,d):52}function Xb(a,b,c,d){return F?V(22,1,a,b,c,d):70}
var Sc=[null,[],[]];function Yb(a,b,c,d){if(F)return V(23,1,a,b,c,d);b>>>=0;c>>>=0;d>>>=0;for(var f=0,g=0;g<c;g++){var l=A()[b>>>2>>>0],m=A()[b+4>>>2>>>0];b+=8;for(var p=0;p<m;p++){var q=x()[l+p>>>0],t=Sc[a];0===q||10===q?((1===a?Aa:I)(Bc(t,0)),t.length=0):t.push(q)}f+=m}A()[d>>>2>>>0]=f;return 0}var Tc=[31,29,31,30,31,30,31,31,30,31,30,31],Uc=[31,28,31,30,31,30,31,31,30,31,30,31];function Vc(a){var b=Array(Cc(a)+1);Dc(a,b,0,b.length);return b}var Wc=(a,b)=>{e().set(a,b>>>0)};
function $b(a,b,c,d){function f(h,u,w){for(h="number"==typeof h?h.toString():h||"";h.length<u;)h=w[0]+h;return h}function g(h,u){return f(h,u,"0")}function l(h,u){function w(jc){return 0>jc?-1:0<jc?1:0}var S;0===(S=w(h.getFullYear()-u.getFullYear()))&&0===(S=w(h.getMonth()-u.getMonth()))&&(S=w(h.getDate()-u.getDate()));return S}function m(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function p(h){var u=h.ab;for(h=new Date((new Date(h.bb+1900,0,1)).getTime());0<u;){var w=h.getMonth(),S=(W(h.getFullYear())?Tc:Uc)[w];if(u>S-h.getDate())u-=S-h.getDate()+1,h.setDate(1),11>w?h.setMonth(w+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+u);break}}w=new Date(h.getFullYear()+1,0,4);u=m(new Date(h.getFullYear(),
0,4));w=m(w);return 0>=l(u,h)?0>=l(w,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}a>>>=0;b>>>=0;c>>>=0;d>>>=0;var q=A()[d+40>>>2>>>0];d={Fb:z()[d>>>2>>>0],Eb:z()[d+4>>>2>>>0],gb:z()[d+8>>>2>>>0],kb:z()[d+12>>>2>>>0],hb:z()[d+16>>>2>>>0],bb:z()[d+20>>>2>>>0],Ua:z()[d+24>>>2>>>0],ab:z()[d+28>>>2>>>0],Pb:z()[d+32>>>2>>>0],Db:z()[d+36>>>2>>>0],Gb:q?P(q):""};c=P(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y",
"%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in q)c=c.replace(new RegExp(t,"g"),q[t]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),y="January February March April May June July August September October November December".split(" ");q={"%a":h=>v[h.Ua].substring(0,3),"%A":h=>
v[h.Ua],"%b":h=>y[h.hb].substring(0,3),"%B":h=>y[h.hb],"%C":h=>g((h.bb+1900)/100|0,2),"%d":h=>g(h.kb,2),"%e":h=>f(h.kb,2," "),"%g":h=>p(h).toString().substring(2),"%G":p,"%H":h=>g(h.gb,2),"%I":h=>{h=h.gb;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":h=>{for(var u=0,w=0;w<=h.hb-1;u+=(W(h.bb+1900)?Tc:Uc)[w++]);return g(h.kb+u,3)},"%m":h=>g(h.hb+1,2),"%M":h=>g(h.Eb,2),"%n":()=>"\n","%p":h=>0<=h.gb&&12>h.gb?"AM":"PM","%S":h=>g(h.Fb,2),"%t":()=>"\t","%u":h=>h.Ua||7,"%U":h=>g(Math.floor((h.ab+7-h.Ua)/7),
2),"%V":h=>{var u=Math.floor((h.ab+7-(h.Ua+6)%7)/7);2>=(h.Ua+371-h.ab-2)%7&&u++;if(u)53==u&&(w=(h.Ua+371-h.ab)%7,4==w||3==w&&W(h.bb)||(u=1));else{u=52;var w=(h.Ua+7-h.ab-1)%7;(4==w||5==w&&W(h.bb%400-1))&&u++}return g(u,2)},"%w":h=>h.Ua,"%W":h=>g(Math.floor((h.ab+7-(h.Ua+6)%7)/7),2),"%y":h=>(h.bb+1900).toString().substring(2),"%Y":h=>h.bb+1900,"%z":h=>{h=h.Db;var u=0<=h;h=Math.abs(h)/60;return(u?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":h=>h.Gb,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");
for(t in q)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),q[t](d)));c=c.replace(/\0\0/g,"%");t=Vc(c);if(t.length>b)return 0;Wc(t,a);return t.length-1}function ac(a,b,c,d){return $b(a>>>0,b>>>0,c>>>0,d>>>0)}var Xc=a=>{try{a()}catch(b){O(b)}};function Yc(){var a=Y,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...f)=>{Zc.push(c);try{return d(...f)}finally{K||(Zc.pop(),G&&1===Z&&0===Zc.length&&(Z=0,U+=1,Xc($c),"undefined"!=typeof Fibers&&Fibers.Qb()))}}:d;return b}
var Z=0,G=null,ad=0,Zc=[],bd={},cd={},dd=0,ed=null,fd=[];function oa(){return new Promise((a,b)=>{ed={resolve:a,reject:b}})}function gd(){var a=hd(65548),b=a+12;A()[a>>>2>>>0]=b;A()[a+4>>>2>>>0]=b+65536;b=Zc[0];var c=bd[b];void 0===c&&(c=dd++,bd[b]=c,cd[c]=b);b=c;z()[a+8>>>2>>>0]=b;return a}function jd(){var a=z()[G+8>>>2>>>0];a=Y[cd[a]];--U;return a()}
function kd(a){if(!K){if(0===Z){var b=!1,c=!1;a((d=0)=>{if(!K&&(ad=d,b=!0,c)){Z=2;Xc(()=>ld(G));"undefined"!=typeof Browser&&Browser.jb.pb&&Browser.jb.resume();d=!1;try{var f=jd()}catch(m){f=m,d=!0}var g=!1;if(!G){var l=ed;l&&(ed=null,(d?l.reject:l.resolve)(f),g=!0)}if(d&&!g)throw f;}});c=!0;b||(Z=1,G=gd(),"undefined"!=typeof Browser&&Browser.jb.pb&&Browser.jb.pause(),Xc(()=>md(G)))}else 2===Z?(Z=0,Xc(nd),od(G),G=null,fd.forEach(Fc)):O(`invalid state: ${Z}`);return ad}}
function cc(a){return kd(b=>{a().then(b)})}F||pc();
var Ic=[Zb,nc,zc,fb,gb,hb,ib,jb,kb,lb,mb,nb,ob,pb,qb,rb,Cb,Db,Sb,Tb,Vb,Wb,Xb,Yb],ab,Y=function(){function a(c,d){Y=c.exports;Y=Yc();Y=pd();oc.push(Y.Ia);Qa.unshift(Y.ba);Oa=d;Ua();return Y}var b=Ea();N++;if(C.instantiateWasm)try{return C.instantiateWasm(b,a)}catch(c){I(`Module.instantiateWasm callback failed with error: ${c}`),ka(c)}Wa||=C.locateFile?Va("ort-wasm-relaxedsimd-threaded.jsep.wasm")?"ort-wasm-relaxedsimd-threaded.jsep.wasm":C.locateFile?C.locateFile("ort-wasm-relaxedsimd-threaded.jsep.wasm",
H):H+"ort-wasm-relaxedsimd-threaded.jsep.wasm":(new URL("ort-wasm-relaxedsimd-threaded.jsep.wasm",import.meta.url)).href;$a(b,function(c){a(c.instance,c.module)}).catch(ka);return{}}();C._OrtInit=(a,b)=>(C._OrtInit=Y.ca)(a,b);C._OrtGetLastError=(a,b)=>(C._OrtGetLastError=Y.da)(a,b);C._OrtCreateSessionOptions=(a,b,c,d,f,g,l,m,p,q)=>(C._OrtCreateSessionOptions=Y.ea)(a,b,c,d,f,g,l,m,p,q);C._OrtAppendExecutionProvider=(a,b)=>(C._OrtAppendExecutionProvider=Y.fa)(a,b);
C._OrtAddFreeDimensionOverride=(a,b,c)=>(C._OrtAddFreeDimensionOverride=Y.ga)(a,b,c);C._OrtAddSessionConfigEntry=(a,b,c)=>(C._OrtAddSessionConfigEntry=Y.ha)(a,b,c);C._OrtReleaseSessionOptions=a=>(C._OrtReleaseSessionOptions=Y.ia)(a);C._OrtCreateSession=(a,b,c)=>(C._OrtCreateSession=Y.ja)(a,b,c);C._OrtReleaseSession=a=>(C._OrtReleaseSession=Y.ka)(a);C._OrtGetInputOutputCount=(a,b,c)=>(C._OrtGetInputOutputCount=Y.la)(a,b,c);C._OrtGetInputName=(a,b)=>(C._OrtGetInputName=Y.ma)(a,b);
C._OrtGetOutputName=(a,b)=>(C._OrtGetOutputName=Y.na)(a,b);C._OrtFree=a=>(C._OrtFree=Y.oa)(a);C._OrtCreateTensor=(a,b,c,d,f,g)=>(C._OrtCreateTensor=Y.pa)(a,b,c,d,f,g);C._OrtGetTensorData=(a,b,c,d,f)=>(C._OrtGetTensorData=Y.qa)(a,b,c,d,f);C._OrtReleaseTensor=a=>(C._OrtReleaseTensor=Y.ra)(a);C._OrtCreateRunOptions=(a,b,c,d)=>(C._OrtCreateRunOptions=Y.sa)(a,b,c,d);C._OrtAddRunConfigEntry=(a,b,c)=>(C._OrtAddRunConfigEntry=Y.ta)(a,b,c);C._OrtReleaseRunOptions=a=>(C._OrtReleaseRunOptions=Y.ua)(a);
C._OrtCreateBinding=a=>(C._OrtCreateBinding=Y.va)(a);C._OrtBindInput=(a,b,c)=>(C._OrtBindInput=Y.wa)(a,b,c);C._OrtBindOutput=(a,b,c,d)=>(C._OrtBindOutput=Y.xa)(a,b,c,d);C._OrtClearBoundOutputs=a=>(C._OrtClearBoundOutputs=Y.ya)(a);C._OrtReleaseBinding=a=>(C._OrtReleaseBinding=Y.za)(a);C._OrtRunWithBinding=(a,b,c,d,f)=>(C._OrtRunWithBinding=Y.Aa)(a,b,c,d,f);C._OrtRun=(a,b,c,d,f,g,l,m)=>(C._OrtRun=Y.Ba)(a,b,c,d,f,g,l,m);C._OrtEndProfiling=a=>(C._OrtEndProfiling=Y.Ca)(a);
C._JsepOutput=(a,b,c)=>(C._JsepOutput=Y.Da)(a,b,c);C._JsepGetNodeName=a=>(C._JsepGetNodeName=Y.Ea)(a);
var J=()=>(J=Y.Fa)(),od=C._free=a=>(od=C._free=Y.Ga)(a),hd=C._malloc=a=>(hd=C._malloc=Y.Ha)(a),Fa=(a,b,c,d,f,g)=>(Fa=Y.Ka)(a,b,c,d,f,g),Ma=()=>(Ma=Y.La)(),lc=(a,b,c,d,f)=>(lc=Y.Ma)(a,b,c,d,f),rc=a=>(rc=Y.Na)(a),Ka=a=>(Ka=Y.Oa)(a),Gc=()=>(Gc=Y.Pa)(),uc=(a,b)=>(uc=Y.Qa)(a,b),mc=a=>(mc=Y.Ra)(a),kc=a=>(kc=Y.Sa)(a),ic=()=>(ic=Y.Ta)(),vc=C.dynCall_ii=(a,b)=>(vc=C.dynCall_ii=Y.Va)(a,b),md=a=>(md=Y.Wa)(a),$c=()=>($c=Y.Xa)(),ld=a=>(ld=Y.Ya)(a),nd=()=>(nd=Y.Za)();C.___start_em_js=816658;C.___stop_em_js=816904;
function pd(){var a=Y;a=Object.assign({},a);var b=d=>()=>d()>>>0,c=d=>f=>d(f)>>>0;a.Fa=b(a.Fa);a.Ha=c(a.Ha);a.emscripten_main_runtime_thread_id=b(a.emscripten_main_runtime_thread_id);a.Sa=c(a.Sa);a.Ta=b(a.Ta);return a}C.stackSave=()=>ic();C.stackRestore=a=>mc(a);C.stackAlloc=a=>kc(a);
C.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":e()[a>>>0]=b;break;case "i8":e()[a>>>0]=b;break;case "i16":ba()[a>>>1>>>0]=b;break;case "i32":z()[a>>>2>>>0]=b;break;case "i64":M[a>>>3]=BigInt(b);break;case "float":fa()[a>>>2>>>0]=b;break;case "double":B()[a>>>3>>>0]=b;break;case "*":A()[a>>>2>>>0]=b;break;default:O(`invalid type for setValue: ${c}`)}};
C.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return e()[a>>>0];case "i8":return e()[a>>>0];case "i16":return ba()[a>>>1>>>0];case "i32":return z()[a>>>2>>>0];case "i64":return M[a>>>3];case "float":return fa()[a>>>2>>>0];case "double":return B()[a>>>3>>>0];case "*":return A()[a>>>2>>>0];default:O(`invalid type for getValue: ${b}`)}};C.UTF8ToString=P;C.stringToUTF8=Ec;C.lengthBytesUTF8=Cc;var qd;Ta=function rd(){qd||sd();qd||(Ta=rd)};
function sd(){0<N||(F?(ja(C),F||tc(Qa),startWorker(C)):(tc(Pa),0<N||qd||(qd=!0,C.calledRun=!0,K||(F||tc(Qa),ja(C),F||tc(Ra)))))}sd();"use strict";C.PTR_SIZE=4;moduleRtn=la;


  return moduleRtn;
}
);
})();
export default ortWasmThreaded;
var isPthread = globalThis.self?.name === 'em-pthread';
var isNode = typeof globalThis.process?.versions?.node == 'string';
if (isNode) isPthread = (await import('worker_threads')).workerData === 'em-pthread';

// When running as a pthread, construct a new instance on startup
isPthread && ortWasmThreaded();
